/// Host-side WIT bindings generated by wasmtime::component::bindgen!.

pub mod decoder {
    wasmtime::component::bindgen!({
        path: "../wit",
        world: "decoder-world",
        exports: { default: async },
    });
}

pub mod enricher {
    wasmtime::component::bindgen!({
        path: "../wit",
        world: "enricher-world",
        exports: { default: async },
    });
}

pub mod sink {
    wasmtime::component::bindgen!({
        path: "../wit",
        world: "sink-world",
        exports: { default: async },
    });
}

// Canonical type aliases — point at the decoder world's generated structs.
// The enricher and sink worlds generate structurally identical types; we
// convert between them in pipeline.rs until we wire up `with` properly.
pub use decoder::liminal::pipeline::types::{EnrichedSwap, EvmLog};
