/// Host-side WIT bindings generated by wasmtime::component::bindgen!.
///
/// One inner module per component world.  The decoder world is generated
/// first because it references all three shared types (EvmLog, Swap,
/// EnrichedSwap via the full `types` interface); those types are then
/// re-exported here as the canonical representations and the enricher/sink
/// worlds reference them via `with` to avoid duplicate struct definitions.
///
/// NOTE: The exact module paths and method names below come from the
/// bindgen! macro expansion.  If a path is wrong the compiler will say so
/// clearly; fix the path, not the architecture.

// ---------------------------------------------------------------------------
// Decoder world  (exports: liminal:pipeline/decode)
// Types generated here are the canonical ones for the whole host.
// ---------------------------------------------------------------------------
pub mod decoder {
    wasmtime::component::bindgen!({
        path: "../wit",
        world: "decoder-world",
        async: true,
    });
}

// Re-export canonical types so the rest of the host uses one definition.
pub use decoder::liminal::pipeline::types::{EnrichedSwap, EvmLog, Swap};

// ---------------------------------------------------------------------------
// Enricher world  (exports: liminal:pipeline/enrich)
// Reuses the canonical types from the decoder world to avoid duplication.
// ---------------------------------------------------------------------------
pub mod enricher {
    wasmtime::component::bindgen!({
        path: "../wit",
        world: "enricher-world",
        async: true,
        with: {
            "liminal:pipeline/types/evm-log":      crate::bindings::EvmLog,
            "liminal:pipeline/types/swap":          crate::bindings::Swap,
            "liminal:pipeline/types/enriched-swap": crate::bindings::EnrichedSwap,
        }
    });
}

// ---------------------------------------------------------------------------
// Sink world  (exports: liminal:pipeline/sink)
// Both the postgres and kafka components implement this same world.
// ---------------------------------------------------------------------------
pub mod sink {
    wasmtime::component::bindgen!({
        path: "../wit",
        world: "sink-world",
        async: true,
        with: {
            "liminal:pipeline/types/evm-log":      crate::bindings::EvmLog,
            "liminal:pipeline/types/swap":          crate::bindings::Swap,
            "liminal:pipeline/types/enriched-swap": crate::bindings::EnrichedSwap,
        }
    });
}
